
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import path from "node:path";
import { defineConfig, env } from "prisma/config";

const envFile = process.env.NODE_ENV === "production" ? ".env.production" : ".env.development";
loadEnv({ path: path.resolve(process.cwd(), envFile) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("MONGODB_URI"),
  },
});
